### ISSUE TITLE
URGENT: Failure to launch `jekyll serve`

### ISSUE THREAD

**Issue by ronaldtse** [geolexica/geolexica-server#147]
This problem was encountered in iev-demo-site. 

```sh
$ bundle exec jekyll serve --trace
Configuration file: /Users/me/src/glossarist/iev-demo-site/_config.yml
 Theme Config file: /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-geolexica-1.5.3/_config.yml
bundler: failed to load command: jekyll (/Users/me/.rbenv/versions/2.6.5/bin/jekyll)
NameError: uninitialized constant Jekyll::Geolexica
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-geolexica-1.5.3/lib/jekyll/geolexica.rb:11:in `<top (required)>'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/zeitwerk-2.4.1/lib/zeitwerk/kernel.rb:33:in `require'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/zeitwerk-2.4.1/lib/zeitwerk/kernel.rb:33:in `require'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-geolexica-1.5.3/lib/jekyll-geolexica.rb:8:in `<top (required)>'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/zeitwerk-2.4.1/lib/zeitwerk/kernel.rb:33:in `require'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/zeitwerk-2.4.1/lib/zeitwerk/kernel.rb:33:in `require'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-4.1.1/lib/jekyll/external.rb:60:in `block in require_with_graceful_fail'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-4.1.1/lib/jekyll/external.rb:57:in `each'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-4.1.1/lib/jekyll/external.rb:57:in `require_with_graceful_fail'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-4.1.1/lib/jekyll/plugin_manager.rb:30:in `require_gems'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-4.1.1/lib/jekyll/plugin_manager.rb:22:in `conscientious_require'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:130:in `setup'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:36:in `initialize'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-4.1.1/lib/jekyll/commands/build.rb:30:in `new'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-4.1.1/lib/jekyll/commands/build.rb:30:in `process'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `each'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-4.1.1/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-4.1.1/exe/jekyll:15:in `<top (required)>'
  /Users/me/.rbenv/versions/2.6.5/bin/jekyll:23:in `load'
  /Users/me/.rbenv/versions/2.6.5/bin/jekyll:23:in `<top (required)>'
```

**Comment by skalee** [comment]
I'll take a look.

**Comment by skalee** [comment]
Fixed in https://github.com/geolexica/geolexica-server/pull/148.
